#!/bin/bash
if [ $# -eq 0 -o "$1" = '--help' ]; then
    echo "GCL: the \`git clone\` that doesn't suck"
    echo
    echo 'Usage:'
    echo
    echo '$ cat ~/.config/git-providers'
    echo 'https://github.com/'
    echo 'c:https://czipperz@github.com/czipperz/'
    echo
    echo '$ gcl c:gcl   # clones gcl for you!'
    echo '...'
    echo '$ gcl robbyrussell/oh-my-zsh   # clones `oh-my-zsh` for you!'
    echo '...'
    exit 1
fi

if [ 1 -eq $(echo "$1" | egrep -c "^(http(s)?|git|ssh)://*") ]; then
    git clone $@ || exit $?
elif [ 1 -eq $(echo "$1" | egrep -c "^[^:]+:.+") ]; then
    nnnn="$(echo "$1" | perl -pe 's/([^:]+:).+/$1/')"
    nn="$(cat "$HOME/.config/git-providers" | wc -l)"
    for (( i=2; i <= $nn; i++ )); do
        hi="$(head -n $i "$HOME/.config/git-providers" | tail -n 1)"
        if [ 1 -eq $(echo "$hi" | egrep -c "^$nnnn") ]; then
            xD="$(echo "$1" | perl -pe 's/[^:]+:(.+)/$1/')"
            shift
            git clone $(echo "$hi" | perl -pe 's/[^:]+:(.+)/$1/')$xD $@ \
                || exit $?
            exit 0
        fi
    done
    echo "Couldn't find provider $(echo "$nnnn" | perl -pe 's/:$//')"
else
    git clone $(head -n 1 "$HOME/.config/git-providers")$@ || exit $?
fi
