#!/bin/bash
clone() {
    echo "git clone $@"
    git clone "$@" || exit -1
}

main() {
    if [ $# -eq 0 -o "$1" = '--help' ]; then
        echo "GCL: the \`git clone\` that doesn't suck"
        echo
        echo 'Usage:'
        echo
        echo '$ cat ~/.config/git-providers'
        echo 'https://github.com/'
        echo 'c:https://czipperz@github.com/czipperz/'
        echo
        echo '$ gcl c:gcl   # clones gcl for you!'
        echo '...'
        echo '$ gcl robbyrussell/oh-my-zsh   # clones `oh-my-zsh` for you!'
        echo '...'
        exit 1
    fi

    if [ 1 -eq $(echo "$1" | grep -c -E -m 1 "^(http(s)?|git|ssh)://.*") ]; then
        local repo="$(echo "$1" | perl -pe 's/(\.git)?$/.git/')"
        shift
        clone "$repo" "$@"
    elif [ 1 -eq $(echo "$1" | grep -c -E -m 1 "^[^:]+:.+") ]; then
        local provider="$(echo "$1" | perl -pe 's/([^:]+:).+/$1/')"
        local lineCount="$(cat "$HOME/.config/git-providers" | wc -l)"
        local line
        local url
        # for line in git-providers that isn't first
        for (( i=2; i <= $lineCount; i++ )); do
            line="$(head -n $i "$HOME/.config/git-providers" | tail -n 1)"
            if [ 1 -eq $(echo "$line" | grep -c -E -m 1 "^$provider") ]; then
                url="$(echo "$1" | perl -pe 's/[^:]+:(.+)/$1/')"
                shift
                clone "$(echo "$url" | perl -pe 's/[^:]+:(.+)/$1/')$url" "$@"
                exit 0
            fi
        done
        echo "Couldn't find provider $(echo "$provider" | perl -pe 's/:$//')"
        exit 1
    else
        local repo="$1"
        local prefix="$(head -n 1 "$HOME/.config/git-providers")"
        shift
        clone "$prefix$repo" "$@"
    fi
}

main "$@"
